// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vadder8_tb__Syms.h"


void Vadder8_tb___024root__trace_chg_0_sub_0(Vadder8_tb___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vadder8_tb___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vadder8_tb___024root__trace_chg_0\n"); );
    // Init
    Vadder8_tb___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vadder8_tb___024root*>(voidSelf);
    Vadder8_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vadder8_tb___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vadder8_tb___024root__trace_chg_0_sub_0(Vadder8_tb___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vadder8_tb___024root__trace_chg_0_sub_0\n"); );
    Vadder8_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    if (VL_UNLIKELY(((vlSelfRef.__Vm_traceActivity[1U] 
                      | vlSelfRef.__Vm_traceActivity
                      [2U])))) {
        bufp->chgBit(oldp+0,(vlSelfRef.adder8_tb__DOT__cin));
        bufp->chgCData(oldp+1,(vlSelfRef.adder8_tb__DOT__a),8);
        bufp->chgCData(oldp+2,(vlSelfRef.adder8_tb__DOT__b),8);
        bufp->chgCData(oldp+3,(((((0x80U & ((0xffffff80U 
                                             & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                            ^ (0xffffff80U 
                                               & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   << 1U) 
                                                  | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      << 1U) 
                                                     & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         << 2U) 
                                                        | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            << 2U) 
                                                           & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               << 3U) 
                                                              | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  << 3U) 
                                                                 & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     << 4U) 
                                                                    | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        << 4U) 
                                                                       & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           << 5U) 
                                                                          | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              << 5U) 
                                                                             & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                << 6U) 
                                                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                << 6U) 
                                                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                                                                << 7U)))))))))))))))) 
                                  | (0x40U & ((0xffffffc0U 
                                               & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                              ^ (0xffffffc0U 
                                                 & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                     << 1U) 
                                                    | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                         ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                        << 1U) 
                                                       & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                            & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                           << 2U) 
                                                          | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                              << 2U) 
                                                             & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                 << 3U) 
                                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                    << 3U) 
                                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                       << 4U) 
                                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                          << 4U) 
                                                                         & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                             << 5U) 
                                                                            | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                << 5U) 
                                                                               & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                                                                << 6U))))))))))))))) 
                                 | ((0x20U & ((0xffffffe0U 
                                               & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                              ^ (0xffffffe0U 
                                                 & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                     << 1U) 
                                                    | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                         ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                        << 1U) 
                                                       & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                            & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                           << 2U) 
                                                          | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                              << 2U) 
                                                             & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                 << 3U) 
                                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                    << 3U) 
                                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                       << 4U) 
                                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                          << 4U) 
                                                                         & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                             | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                                                            << 5U)))))))))))) 
                                    | (0x10U & ((0xfffffff0U 
                                                 & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                                ^ (0xfffffff0U 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       << 1U) 
                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          << 1U) 
                                                         & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             << 2U) 
                                                            | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                << 2U) 
                                                               & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   << 3U) 
                                                                  | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                      << 3U) 
                                                                     & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                          & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                         | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                            & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                                                        << 4U)))))))))))) 
                                | (((8U & ((0xfffffff8U 
                                            & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                           ^ (0xfffffff8U 
                                              & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                  << 1U) 
                                                 | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                     << 1U) 
                                                    & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                         & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                        << 2U) 
                                                       | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                            ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                           << 2U) 
                                                          & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                              | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                 & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                                             << 3U)))))))) 
                                    | (4U & ((0xfffffffcU 
                                              & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                             ^ (0xfffffffcU 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    << 1U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       << 1U) 
                                                      & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                                         << 2U))))))) 
                                   | ((2U & ((0xfffffffeU 
                                              & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                             ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                                << 1U))) 
                                      | (1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__cin))))))),8);
        bufp->chgBit(oldp+4,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 7U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                >> 7U) 
                                               & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   >> 6U) 
                                                  | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      >> 6U) 
                                                     & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         >> 5U) 
                                                        | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            >> 5U) 
                                                           & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               >> 4U) 
                                                              | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  >> 4U) 
                                                                 & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     >> 3U) 
                                                                    | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        >> 3U) 
                                                                       & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           >> 2U) 
                                                                          | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              >> 2U) 
                                                                             & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                >> 1U) 
                                                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                >> 1U) 
                                                                                & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))))))))))))))));
        bufp->chgBit(oldp+5,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 7U) & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                >> 6U) 
                                               | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   >> 6U) 
                                                  & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      >> 5U) 
                                                     | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         >> 5U) 
                                                        & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            >> 4U) 
                                                           | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               >> 4U) 
                                                              & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  >> 3U) 
                                                                 | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     >> 3U) 
                                                                    & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        >> 2U) 
                                                                       | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           >> 2U) 
                                                                          & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              >> 1U) 
                                                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                >> 1U) 
                                                                                & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))))))))));
        bufp->chgBit(oldp+6,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 7U) ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                >> 6U) 
                                               | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   >> 6U) 
                                                  & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      >> 5U) 
                                                     | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         >> 5U) 
                                                        & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            >> 4U) 
                                                           | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               >> 4U) 
                                                              & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  >> 3U) 
                                                                 | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     >> 3U) 
                                                                    & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        >> 2U) 
                                                                       | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           >> 2U) 
                                                                          & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              >> 1U) 
                                                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                >> 1U) 
                                                                                & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))))))))));
        bufp->chgBit(oldp+7,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                    >> 7U))));
        bufp->chgBit(oldp+8,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                    >> 7U))));
        bufp->chgBit(oldp+9,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 6U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                >> 6U) 
                                               & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   >> 5U) 
                                                  | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      >> 5U) 
                                                     & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         >> 4U) 
                                                        | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            >> 4U) 
                                                           & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               >> 3U) 
                                                              | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  >> 3U) 
                                                                 & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     >> 2U) 
                                                                    | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        >> 2U) 
                                                                       & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           >> 1U) 
                                                                          | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              >> 1U) 
                                                                             & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))))))))))))));
        bufp->chgBit(oldp+10,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 6U) & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 5U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 5U) 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 4U) 
                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 4U) 
                                                         & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 3U) 
                                                            | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 3U) 
                                                               & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   >> 2U) 
                                                                  | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                      >> 2U) 
                                                                     & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                          & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                         >> 1U) 
                                                                        | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                            >> 1U) 
                                                                           & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))))))));
        bufp->chgBit(oldp+11,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 6U) ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 5U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 5U) 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 4U) 
                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 4U) 
                                                         & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 3U) 
                                                            | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 3U) 
                                                               & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   >> 2U) 
                                                                  | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                      >> 2U) 
                                                                     & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                          & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                         >> 1U) 
                                                                        | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                            >> 1U) 
                                                                           & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))))))));
        bufp->chgBit(oldp+12,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 6U))));
        bufp->chgBit(oldp+13,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 6U))));
        bufp->chgBit(oldp+14,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 5U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 5U) 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 4U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 4U) 
                                                      & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 3U) 
                                                         | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 3U) 
                                                            & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 2U) 
                                                               | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   >> 2U) 
                                                                  & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                      >> 1U) 
                                                                     | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                          ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                         >> 1U) 
                                                                        & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))))))))))));
        bufp->chgBit(oldp+15,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 5U) & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 4U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 4U) 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 3U) 
                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 3U) 
                                                         & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 2U) 
                                                            | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 2U) 
                                                               & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   >> 1U) 
                                                                  | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                      >> 1U) 
                                                                     & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))))));
        bufp->chgBit(oldp+16,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 5U) ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 4U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 4U) 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 3U) 
                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 3U) 
                                                         & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 2U) 
                                                            | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 2U) 
                                                               & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   >> 1U) 
                                                                  | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                      >> 1U) 
                                                                     & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))))));
        bufp->chgBit(oldp+17,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 5U))));
        bufp->chgBit(oldp+18,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 5U))));
        bufp->chgBit(oldp+19,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 4U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 4U) 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 3U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 3U) 
                                                      & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 2U) 
                                                         | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 2U) 
                                                            & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 1U) 
                                                               | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   >> 1U) 
                                                                  & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))))))))));
        bufp->chgBit(oldp+20,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 4U) & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 3U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 3U) 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 2U) 
                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 2U) 
                                                         & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 1U) 
                                                            | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 1U) 
                                                               & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))));
        bufp->chgBit(oldp+21,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 4U) ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 3U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 3U) 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 2U) 
                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 2U) 
                                                         & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 1U) 
                                                            | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 1U) 
                                                               & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))));
        bufp->chgBit(oldp+22,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 4U))));
        bufp->chgBit(oldp+23,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 4U))));
        bufp->chgBit(oldp+24,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 3U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 3U) 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 2U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 2U) 
                                                      & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 1U) 
                                                         | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 1U) 
                                                            & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))))))));
        bufp->chgBit(oldp+25,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 3U) & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 2U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 2U) 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 1U) 
                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 1U) 
                                                         & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))));
        bufp->chgBit(oldp+26,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 3U) ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 2U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 2U) 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 1U) 
                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 1U) 
                                                         & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))));
        bufp->chgBit(oldp+27,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 3U))));
        bufp->chgBit(oldp+28,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 3U))));
        bufp->chgBit(oldp+29,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 2U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 2U) 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 1U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 1U) 
                                                      & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))))));
        bufp->chgBit(oldp+30,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 2U) & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 1U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 1U) 
                                                   & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))));
        bufp->chgBit(oldp+31,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 2U) ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 1U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 1U) 
                                                   & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))));
        bufp->chgBit(oldp+32,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 2U))));
        bufp->chgBit(oldp+33,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 2U))));
        bufp->chgBit(oldp+34,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 1U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 1U) 
                                                & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))));
        bufp->chgBit(oldp+35,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 1U) & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))));
        bufp->chgBit(oldp+36,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                      >> 1U) ^ (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))));
        bufp->chgBit(oldp+37,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 1U))));
        bufp->chgBit(oldp+38,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     >> 1U))));
        bufp->chgBit(oldp+39,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                         ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                        & (IData)(vlSelfRef.adder8_tb__DOT__cin))))));
        bufp->chgBit(oldp+40,((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                               & (IData)(vlSelfRef.adder8_tb__DOT__cin))));
        bufp->chgBit(oldp+41,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__cin)))));
        bufp->chgBit(oldp+42,((1U & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)))));
        bufp->chgBit(oldp+43,((1U & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)))));
    }
}

void Vadder8_tb___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vadder8_tb___024root__trace_cleanup\n"); );
    // Init
    Vadder8_tb___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vadder8_tb___024root*>(voidSelf);
    Vadder8_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    vlSymsp->__Vm_activity = false;
    vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[2U] = 0U;
}
