// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vadder8_tb__Syms.h"


VL_ATTR_COLD void Vadder8_tb___024root__trace_init_sub__TOP__0(Vadder8_tb___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vadder8_tb___024root__trace_init_sub__TOP__0\n"); );
    Vadder8_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->pushPrefix("adder8_tb", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+1,0,"cin",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+2,0,"a",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+3,0,"b",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+4,0,"sum",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+5,0,"cout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("adder8_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+1,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+2,0,"x",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+3,0,"y",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+4,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+5,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+5,0,"net40",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+6,0,"net39",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+7,0,"net38",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+8,0,"net37",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+9,0,"net36",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+10,0,"net35",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+11,0,"net34",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+12,0,"net33",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+13,0,"net32",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"net31",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"net30",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"net29",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+17,0,"net28",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+18,0,"net27",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+19,0,"net26",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+20,0,"net25",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+21,0,"net24",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+22,0,"net23",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+23,0,"net22",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+24,0,"net21",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+25,0,"net20",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+26,0,"net19",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+27,0,"net18",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+28,0,"net17",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"net16",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+30,0,"net15",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+31,0,"net14",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+32,0,"net13",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+33,0,"net12",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"net11",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+35,0,"net10",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+36,0,"net9",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+37,0,"net8",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"net7",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"net6",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+40,0,"net5",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+41,0,"net4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"net3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"net2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+44,0,"net1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+1,0,"net0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+2,0,"vec0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+3,0,"vec1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vadder8_tb___024root__trace_init_top(Vadder8_tb___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vadder8_tb___024root__trace_init_top\n"); );
    Vadder8_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vadder8_tb___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vadder8_tb___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vadder8_tb___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vadder8_tb___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vadder8_tb___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vadder8_tb___024root__trace_register(Vadder8_tb___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vadder8_tb___024root__trace_register\n"); );
    Vadder8_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vadder8_tb___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vadder8_tb___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vadder8_tb___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vadder8_tb___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vadder8_tb___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vadder8_tb___024root__trace_const_0\n"); );
    // Init
    Vadder8_tb___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vadder8_tb___024root*>(voidSelf);
    Vadder8_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
}

VL_ATTR_COLD void Vadder8_tb___024root__trace_full_0_sub_0(Vadder8_tb___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vadder8_tb___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vadder8_tb___024root__trace_full_0\n"); );
    // Init
    Vadder8_tb___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vadder8_tb___024root*>(voidSelf);
    Vadder8_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vadder8_tb___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vadder8_tb___024root__trace_full_0_sub_0(Vadder8_tb___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vadder8_tb___024root__trace_full_0_sub_0\n"); );
    Vadder8_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelfRef.adder8_tb__DOT__cin));
    bufp->fullCData(oldp+2,(vlSelfRef.adder8_tb__DOT__a),8);
    bufp->fullCData(oldp+3,(vlSelfRef.adder8_tb__DOT__b),8);
    bufp->fullCData(oldp+4,(((((0x80U & ((0xffffff80U 
                                          & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                         ^ (0xffffff80U 
                                            & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                << 1U) 
                                               | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   << 1U) 
                                                  & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      << 2U) 
                                                     | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         << 2U) 
                                                        & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            << 3U) 
                                                           | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               << 3U) 
                                                              & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  << 4U) 
                                                                 | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     << 4U) 
                                                                    & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        << 5U) 
                                                                       | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           << 5U) 
                                                                          & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              << 6U) 
                                                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                << 6U) 
                                                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                                                                << 7U)))))))))))))))) 
                               | (0x40U & ((0xffffffc0U 
                                            & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                           ^ (0xffffffc0U 
                                              & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                  << 1U) 
                                                 | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                     << 1U) 
                                                    & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                         & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                        << 2U) 
                                                       | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                            ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                           << 2U) 
                                                          & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                              << 3U) 
                                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                 << 3U) 
                                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                    << 4U) 
                                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                       << 4U) 
                                                                      & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                           & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                          << 5U) 
                                                                         | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                             << 5U) 
                                                                            & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                                                               << 6U))))))))))))))) 
                              | ((0x20U & ((0xffffffe0U 
                                            & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                           ^ (0xffffffe0U 
                                              & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                  << 1U) 
                                                 | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                     << 1U) 
                                                    & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                         & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                        << 2U) 
                                                       | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                            ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                           << 2U) 
                                                          & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                              << 3U) 
                                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                 << 3U) 
                                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                    << 4U) 
                                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                       << 4U) 
                                                                      & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                           & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                          | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                             & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                                                         << 5U)))))))))))) 
                                 | (0x10U & ((0xfffffff0U 
                                              & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                             ^ (0xfffffff0U 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    << 1U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       << 1U) 
                                                      & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          << 2U) 
                                                         | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             << 2U) 
                                                            & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                << 3U) 
                                                               | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   << 3U) 
                                                                  & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                      | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                          ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                         & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                                                     << 4U)))))))))))) 
                             | (((8U & ((0xfffffff8U 
                                         & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                            ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                        ^ (0xfffffff8U 
                                           & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                               << 1U) 
                                              | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                  << 1U) 
                                                 & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                     << 2U) 
                                                    | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                         ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                        << 2U) 
                                                       & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                            & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                           | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                              & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                                          << 3U)))))))) 
                                 | (4U & ((0xfffffffcU 
                                           & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                          ^ (0xfffffffcU 
                                             & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 << 1U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    << 1U) 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                                      << 2U))))))) 
                                | ((2U & ((0xfffffffeU 
                                           & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b))) 
                                          ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 & (IData)(vlSelfRef.adder8_tb__DOT__cin))) 
                                             << 1U))) 
                                   | (1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                            ^ (IData)(vlSelfRef.adder8_tb__DOT__cin))))))),8);
    bufp->fullBit(oldp+5,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 7U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                             >> 7U) 
                                            & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                >> 6U) 
                                               | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   >> 6U) 
                                                  & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      >> 5U) 
                                                     | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         >> 5U) 
                                                        & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            >> 4U) 
                                                           | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               >> 4U) 
                                                              & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  >> 3U) 
                                                                 | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     >> 3U) 
                                                                    & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        >> 2U) 
                                                                       | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           >> 2U) 
                                                                          & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              >> 1U) 
                                                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                >> 1U) 
                                                                                & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))))))))))))))));
    bufp->fullBit(oldp+6,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 7U) & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                             >> 6U) 
                                            | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                >> 6U) 
                                               & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   >> 5U) 
                                                  | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      >> 5U) 
                                                     & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         >> 4U) 
                                                        | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            >> 4U) 
                                                           & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               >> 3U) 
                                                              | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  >> 3U) 
                                                                 & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     >> 2U) 
                                                                    | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        >> 2U) 
                                                                       & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           >> 1U) 
                                                                          | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              >> 1U) 
                                                                             & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))))))))));
    bufp->fullBit(oldp+7,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 7U) ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                             >> 6U) 
                                            | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                >> 6U) 
                                               & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   >> 5U) 
                                                  | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      >> 5U) 
                                                     & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         >> 4U) 
                                                        | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            >> 4U) 
                                                           & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               >> 3U) 
                                                              | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  >> 3U) 
                                                                 & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     >> 2U) 
                                                                    | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        >> 2U) 
                                                                       & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           >> 1U) 
                                                                          | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              >> 1U) 
                                                                             & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))))))))));
    bufp->fullBit(oldp+8,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                 >> 7U))));
    bufp->fullBit(oldp+9,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                 >> 7U))));
    bufp->fullBit(oldp+10,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 6U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 6U) 
                                             & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 5U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 5U) 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 4U) 
                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 4U) 
                                                         & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 3U) 
                                                            | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 3U) 
                                                               & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   >> 2U) 
                                                                  | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                      >> 2U) 
                                                                     & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                          & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                         >> 1U) 
                                                                        | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                            >> 1U) 
                                                                           & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))))))))))))));
    bufp->fullBit(oldp+11,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 6U) & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 5U) 
                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 5U) 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 4U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 4U) 
                                                      & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 3U) 
                                                         | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 3U) 
                                                            & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 2U) 
                                                               | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   >> 2U) 
                                                                  & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                      >> 1U) 
                                                                     | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                          ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                         >> 1U) 
                                                                        & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))))))));
    bufp->fullBit(oldp+12,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 6U) ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 5U) 
                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 5U) 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 4U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 4U) 
                                                      & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 3U) 
                                                         | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 3U) 
                                                            & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 2U) 
                                                               | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   >> 2U) 
                                                                  & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                      >> 1U) 
                                                                     | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                          ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                         >> 1U) 
                                                                        & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                              & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))))))));
    bufp->fullBit(oldp+13,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 6U))));
    bufp->fullBit(oldp+14,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 6U))));
    bufp->fullBit(oldp+15,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 5U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 5U) 
                                             & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 4U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 4U) 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 3U) 
                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 3U) 
                                                         & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 2U) 
                                                            | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 2U) 
                                                               & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   >> 1U) 
                                                                  | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                      >> 1U) 
                                                                     & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                            ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                           & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))))))))))));
    bufp->fullBit(oldp+16,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 5U) & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 4U) 
                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 4U) 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 3U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 3U) 
                                                      & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 2U) 
                                                         | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 2U) 
                                                            & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 1U) 
                                                               | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   >> 1U) 
                                                                  & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))))));
    bufp->fullBit(oldp+17,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 5U) ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 4U) 
                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 4U) 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 3U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 3U) 
                                                      & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 2U) 
                                                         | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 2U) 
                                                            & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 1U) 
                                                               | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                   >> 1U) 
                                                                  & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                         ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                        & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))))));
    bufp->fullBit(oldp+18,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 5U))));
    bufp->fullBit(oldp+19,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 5U))));
    bufp->fullBit(oldp+20,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 4U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 4U) 
                                             & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 3U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 3U) 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 2U) 
                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 2U) 
                                                         & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 1U) 
                                                            | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                >> 1U) 
                                                               & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                     & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))))))))));
    bufp->fullBit(oldp+21,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 4U) & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 3U) 
                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 3U) 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 2U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 2U) 
                                                      & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 1U) 
                                                         | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 1U) 
                                                            & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))));
    bufp->fullBit(oldp+22,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 4U) ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 3U) 
                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 3U) 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 2U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 2U) 
                                                      & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 1U) 
                                                         | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                              ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                             >> 1U) 
                                                            & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                                  & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))))));
    bufp->fullBit(oldp+23,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 4U))));
    bufp->fullBit(oldp+24,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 4U))));
    bufp->fullBit(oldp+25,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 3U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 3U) 
                                             & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 2U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 2U) 
                                                   & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 1U) 
                                                      | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                           ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                          >> 1U) 
                                                         & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                                ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                               & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))))))));
    bufp->fullBit(oldp+26,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 3U) & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 2U) 
                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 2U) 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 1U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 1U) 
                                                      & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))));
    bufp->fullBit(oldp+27,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 3U) ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 2U) 
                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 2U) 
                                                & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 1U) 
                                                   | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                        ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                       >> 1U) 
                                                      & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                            & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))))));
    bufp->fullBit(oldp+28,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 3U))));
    bufp->fullBit(oldp+29,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 3U))));
    bufp->fullBit(oldp+30,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 2U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 2U) 
                                             & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 1U) 
                                                | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                     ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                    >> 1U) 
                                                   & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                          ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                         & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))))));
    bufp->fullBit(oldp+31,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 2U) & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 1U) 
                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 1U) 
                                                & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))));
    bufp->fullBit(oldp+32,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 2U) ^ ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 1U) 
                                             | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                 >> 1U) 
                                                & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                       ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                      & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))))));
    bufp->fullBit(oldp+33,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 2U))));
    bufp->fullBit(oldp+34,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 2U))));
    bufp->fullBit(oldp+35,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 1U) | ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                               ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                              >> 1U) 
                                             & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                   & (IData)(vlSelfRef.adder8_tb__DOT__cin))))))));
    bufp->fullBit(oldp+36,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 1U) & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                             | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))));
    bufp->fullBit(oldp+37,((1U & ((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                    ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                   >> 1U) ^ (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                              & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                             | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                                 ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                                & (IData)(vlSelfRef.adder8_tb__DOT__cin)))))));
    bufp->fullBit(oldp+38,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 1U))));
    bufp->fullBit(oldp+39,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  >> 1U))));
    bufp->fullBit(oldp+40,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   & (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  | (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                      ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                     & (IData)(vlSelfRef.adder8_tb__DOT__cin))))));
    bufp->fullBit(oldp+41,((((IData)(vlSelfRef.adder8_tb__DOT__a) 
                             ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                            & (IData)(vlSelfRef.adder8_tb__DOT__cin))));
    bufp->fullBit(oldp+42,((1U & (((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                   ^ (IData)(vlSelfRef.adder8_tb__DOT__b)) 
                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__cin)))));
    bufp->fullBit(oldp+43,((1U & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                  & (IData)(vlSelfRef.adder8_tb__DOT__b)))));
    bufp->fullBit(oldp+44,((1U & ((IData)(vlSelfRef.adder8_tb__DOT__a) 
                                  ^ (IData)(vlSelfRef.adder8_tb__DOT__b)))));
}
